### ISSUE TITLE
Where is the $J_{LIPO}$ in the code? 

### ISSUE THREAD

**Issue by JeremyLinky** [51616/marl-lipo#2]
Hi, could you tell me where is the $J_{LIPO}$ in the code?

**Comment by 51616** [comment]
You can see the details in the loss computation here
https://github.com/51616/marl-lipo/blob/main/coop_marl/agents/incompat_mappo_z.py#L237C21-L244C83
we use the `minimize_reward` flag to indicate which batch to maximize or minimize the expected return. Then, the additional MI loss is defined here https://github.com/51616/marl-lipo/blob/main/coop_marl/agents/incompat_mappo_z.py#L191C9-L201C70
